[env:esp32-c6-supermini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags = 
    ; Ativação da porta USB nativa do ESP32-C6
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; Resolve a incompatibilidade do rádio com chips RISC-V
    -D XTOS_DISABLE_ALL_INTERRUPTS=0
    -D "XTOS_RESTORE_INTLEVEL(x)="

lib_deps =
    mikalhart/TinyGPSPlus@^1.0.3
    adafruit/Adafruit ADXL375@^1.1.2
    adafruit/Adafruit Unified Sensor@^1.1.14
    robtillaart/MS5611@^0.4.0
    adafruit/Adafruit BMP280 Library@^2.6.8