; PlatformIO Project Configuration File

[env:nodemcu-32s]
platform = espressif32 @ 6.5.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
; Ensina o compilador a usar apenas o arquivo do foguete
build_src_filter = +<main_foguete.cpp> -<main_estacao.cpp>
lib_deps = 
    mikem/RadioHead @ ^1.120
    mikalhart/TinyGPSPlus @ ^1.0.3
    robtillaart/MS5611 @ ^0.3.8
    adafruit/Adafruit ADXL375 @ ^1.1.2
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit Unified Sensor @ ^1.1.14

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
; Ensina o compilador a usar apenas o arquivo da estação de solo
build_src_filter = +<main_estacao.cpp> -<main_foguete.cpp>
lib_deps = 
    mikem/RadioHead @ ^1.120
